id: legacy
title: Systèmes antérieurs (IE11)
description: Ce package est utilisé de manière globale pour la compatibilité Internet Explorer 11 du Design System de l'Etat.
styles:
  - core
follow:
  styles:
    - radios
    - navigation
    - sidemenu
    - skiplinks
