id: legacy
title: Systèmes antérieurs
description: Ce package est utilisé de manière globale pour la compatibilité Internet Explorer 11 du Design System de l'Etat.
wrapper: col-8
styles:
  - core
follow:
  styles:
    - radios
    - navigation
    - sidemenu
    - skiplinks
